on: [workflow_call]
jobs:
  build-packages:
    strategy:
        matrix:
          runner: [ubuntu-22.04, buildjet-4vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: chainguard-dev/actions/melange-build@main
        with:
          archs: host
          config: ${{ github.workspace }}/melange.yaml
          sign-with-temporary-key: true
      - name: Determine tag based on melange build
        run: |
          PACKAGE_VERSION=$(yq '.package.version' <melange.yaml)
          PACKAGE_EPOCH=$(yq '.package.epoch' <melange.yaml)
          RELEASE_TAG=$PACKAGE_VERSION-r$PACKAGE_EPOCH
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo $RELEASE_TAG > RELEASE_TAG
          echo "Determined tag: $RELEASE_TAG"
      - name: Verify that tag doesn't exist yet
        run: |
          git ls-remote --tags --exit-code origin $RELEASE_TAG && echo "Tag exists already" && exit 1 || echo "Tag doesn't exist yet"
      - uses: actions/upload-artifact@v3
        with:
          path: packages
      - uses: actions/upload-artifact@v3
        with:
          path: RELEASE_TAG
  release-packages:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    needs: build-packages
    steps:
      - uses: actions/download-artifact@v3
      - name: Read tag into variable
        run: |
          RELEASE_TAG=$(<RELEASE_TAG)
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "Read tag: $RELEASE_TAG"
      - name: Flatten repository output
        run: |
          # Turns aarch64/some-package.apk into aarch64_some-package.apk
          # Neccesary since GitHub releases has no folder support
          cd packages && find * -type f | sed 'h;y/\//_/;H;g;s/\n/ /g;s/^/mv -v /' | sh
      - name: Release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        with:
          tag: ${{env.RELEASE_TAG}}
          artifacts: packages/*